version: '3.1'
services:
  mysql:
    image: ubuntu/mysql:8.0-22.04_beta
    container_name: mysql-db
    hostname: mysql-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootuser
      MYSQL_PASSWORD: passw0rd
      MYSQL_USER: user
      MYSQL_DATABASE: todo_app_development
      TZ: Asia/Tokyo

  phpmyadmin:
    image: phpmyadmin
    container_name: mysql-mgr
    hostname: mysql-mgr
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootuser
  
  web:
    image: myubuntu
    container_name: myubuntu
    hostname: myubuntu
    ports: 
      - 3000:3000
      - 3001:3001
      - 3002:3002
    tty: true
